FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_BACKEND_BASE_URL=http://localhost
ENV VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]