services:
  ontrack_db:
    image: mongo:latest
    container_name: ontrack_db
    ports:
      - "127.0.0.1:${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE=ontrack
    volumes:
      - ontrack_db_data:/data/db

  ontrack_backend:
    build: ./backend
    container_name: ontrack_backend
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8000
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - ontrack_db

  ontrack_frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_BASE_URL=${BACKEND_BASE_URL}
    container_name: ontrack_frontend
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:80"
    depends_on:
      - ontrack_backend

volumes:
  ontrack_db_data:
