services:
  ontrack_frontend:
    container_name: ontrack_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  ontrack_backend:
    container_name: ontrack_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - JWT_ACCESS_SECRET=my-super-secret
      - JWT_REFRESH_SECRET=my-super-refresh-secret
    depends_on:
      - ontrack_db

  ontrack_db:
    container_name: ontrack_db
    image: mongo:8.0.13
    volumes:
      - ontrack_db_data:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  ontrack_db_data:
